In [10]:
import numpy as np
import pandas as pd
import csv
import os
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [4]:
os.listdir()

['.ipynb_checkpoints', 'Data.csv', 'Day_1.ipynb']

In [5]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[ : , :-1].values
Y = dataset.iloc[ : , 3].values

dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [6]:
##replace nulls with average
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#transform calculates the missing values, using mean as replacement value, to replace the 2nd and 3rd col, you need to select 1:3 as python doesn't take the upper bound data
imputer = imputer.fit(X[ : , 1:3])
#transform adds in the missing values
X[ : , 1:3] = imputer.transform(X[ : , 1:3])

In [7]:
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])

In [13]:
###Creating a dummy variable
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [16]:
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)

print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)
print(X_train)
print(X_test)
print(y_train)
print(y_test)


[[0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])
print(X_train)
print(X_test)

[[0.0 1.0 0.0 -0.5773502691896258 1.2909944487358056 -0.19159184384578545
  -1.0781259408412425]
 [0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834
  -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7745966692414834 0.566708506533324
  0.633562432710455]
 [0.0 1.0 0.0 -0.5773502691896258 1.2909944487358056 -0.30453019390224867
  -0.30786617274297867]
 [0.0 1.0 0.0 -0.5773502691896258 1.2909944487358056 -1.9018011447007988
  -1.420463615551582]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7745966692414834 1.1475343068237058
  1.232653363453549]
 [0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834 1.4379472069688968
  1.5749910381638885]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7745966692414834 -0.7401495441200351
  -0.5646194287757332]]
[[0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834 -1.4661817944830124
  -0.9069571034860727]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7745966692414834
  -0.44973664397484414 0.2056403393225306]]
